name: Farm Config
on:
  push:
    branches:
      - develop
    paths:
      - 'packages/farms/constants/**'
      - 'packages/tokens/**'
      - '!packages/tokens/src/common.ts'
      - '!packages/tokens/src/helpers.ts'
      - '!packages/tokens/src/index.ts'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      HAVE_CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
    name: Publish Farm Config to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Set up node@18
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build package
        run: pnpm build:packages

      - name: Test
        run: pnpm test:config

      - name: Build list
        run: pnpm turbo run build --filter=@pancakeswap/farms

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        if: ${{ env.HAVE_CLOUDFLARE_TOKEN == 'true' }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b82548875bdb333ff5edcca4d076f88d
          projectName: farms-config
          directory: ./packages/farms/lists
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'develop' && 'master' ||  null  }}
