name: Farm Config
on:
  pull_request:
    paths:
      - 'packages/farms/constants/**'
      - 'packages/tokens/**'
      - '!packages/tokens/common.ts'
      - '!packages/tokens/helpers.ts'
      - '!packages/tokens/index.ts'
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish Farm Config to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test:config

      - name: Build list
        run: yarn turbo run build --filter=@pancakeswap/farms

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b82548875bdb333ff5edcca4d076f88d
          projectName: farms-config
          directory: ./packages/farms/lists
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'develop' && 'main' ||  null  }}
