name: Check TS Errors

on:
  pull_request:

jobs:
  ts-check:
    name: Typescript Error Check
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up node@18
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build package
        run: pnpm build:packages

      - name: Get diff lines
        id: diff
        uses: Equip-Collaboration/diff-line-numbers@v1.0.0
        with:
          include: '["\\.tsx?$"]'

      - name: Detecting files changed
        id: files
        uses: umani/changed-files@v4.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^.*\.tsx?$'

      - name: List files changed (you can remove this step, for monitoring only)
        run: |
          echo 'Changed: ${{ steps.files.outputs.changed }}'
          echo 'Files modified: ${{steps.files.outputs.files_updated}}'
          echo 'Files added: ${{steps.files.outputs.files_created}}'
          echo 'Files removed: ${{steps.files.outputs.files_deleted}}'

      - name: Check typescript errors
        uses: chefjackson/action-check-typescript@v1.1.3
        if: steps.files.outputs.changed == 'true'
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          use-check: true
          list-all-errors: false
          check-fail-mode: errors_in_pr
          files-changed: ${{steps.files.outputs.files_updated}}
          files-added: ${{steps.files.outputs.files_created}}
          files-deleted: ${{steps.files.outputs.files_deleted}}
          line-numbers: ${{steps.diff.outputs.lineNumbers}}
          output-behaviour: both
          comment-behaviour: edit
          ts-config-path: ./apps/web/tsconfig.json
